services:
  booster-web-server-db:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=50
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=booster_web_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    ports:
      - '5455:5432'
    volumes:
      - ./booster-web-server-db:/var/lib/postgresql/data
    networks:
      - booster-web-server-network
volumes:
  booster-web-server-db:
    driver: local

networks:
  booster-web-server-network:
    name: booster-web-server-network
