services:

  booster-web-server:
    depends_on:
      - booster-web-server-db
    image: "booster-web-server"
    container_name: "booster-web-server"
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booster-web-server-db:5432/booster_web_server
    networks:
      - booster-network

  booster-web-server-db:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=50
    image: postgres:latest
    container_name: "booster-web-server-db"
    restart: always
    environment:
      - POSTGRES_DB=booster_web_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    ports:
      - '5455:5432'
    networks:
      - booster-network

networks:
  booster-network:
    name: booster-network
