spring:
  application:
    name: booster-web-server
  liquibase:
    change-log: db/changelog.xml
  datasource:
    url: ${DATASOURCE_URL}
    username: root
    password: pass
  config:
    import: optional:classpath:.env[.properties]

server:
  port: 8090
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 10s
    threads:
      max: 50
      min-spare: 5

logging:
  level:
    booster.webserver: DEBUG
